cmd/korrel8/cmd/common.go
This change discards rule files which don't have the '.yaml', '.yml' or '.json' extension. It avoids returning an error when a rule directory contains a Vim swap file for instance.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
=> cmd/korrel8: skip rule files other than YAML and JSON

.github/workflows/go.yml, cmd/korrel8r/cmd/common.go, cmd/korrel8r/cmd/root.go, pkg/domains/alert/alert.go, pkg/domains/alert/openshift.go, pkg/domains/metric/metric.go
This change adds CLI options to provide URLs of the metrics, logs and alerts APIs instead of relying on the built-in OpenShift routes. This is a first step in decoupling korrel8r from OpenShift and making it platform-agnostic.
cc @alanconway
=> Add command-line flags to pass URLs

pkg/domains/k8s/k8s_test.go, rules/k8s.yaml
`PodToAlert` returns alerts that match a specific pod and `NamespaceToAlert`  returns alerts for a given namespace.
This change also introduces a `NamespacedResourceToNamespace` rule that start from a namespaced objet to the containing namespace. Starting from a k8s object, it can be useful to return all alerts related to the namespace even if the alerts don't match the object.
=> Add PodToAlert and NamespaceToAlert rules

cmd/korrel8r/webui/correlate.html.go, cmd/korrel8r/webui/stores.go
The segment after `/stores`/ is supposed to be the domain name while it was the class name. As such links to k8s classes were broken and returned 404.
=> Fix store URLs in the correlate web page

.gitignore, hack/kind/README.md, hack/kind/config/kustomization.yaml, hack/kind/generate.sh, hack/kind/jsonnet/ingress.libsonnet, hack/kind/manifests/ingress-dashboard.yaml, hack/kind/setup.sh
Eventually korrel8r should be able to integrate other Kubernetes consoles than OCP.
I've looked at different dashboard solutions for Kubernetes and couldn't find anything better than the official upstream dashboards. While it is a bit limited, alternative solutions had their own flaws:
* not fully open-source (e.g. Lens).
* Electron applications hence desktop-only.
* didn't provide more features (e.g. Headlamp).
=> Deploy upstream Kubernetes dashboard

hack/openshift/Makefile, hack/openshift/README.md, hack/openshift/deploy.sh, hack/openshift/manifests/lokistack.yaml
This PR adds `deploy.sh` inside `hack/openshift`. The script makes it easy to debug and maintain the required steps for Korrel8r to work. 
This doesn't change the way initially implemented steps were present in Makefile
=> feat: add deploy script to install the required operators and resources on OpenShift

Makefile
This PR updates the image-build target to include the name of the Dockerfile. Addresses #95
=> fix: update image build target to include name of the Dockerfile

.github/workflows/build.yml, Makefile, hack/shellcheck.sh, hack/wait.sh
This PR adds `shellcheck` target which installs shellcheck tool locally. `make lint` will also run shellcheck
=> feat: add shellcheck make target

hack/openshift/Makefile, hack/openshift/config/resources/netobserv/kustomization.yaml, hack/openshift/config/resources/netobserv/namespace.yaml, hack/wait.sh
This change updates following:
* Makefile to include check in case of undefined storageclass. also fixes some indentation issues.
* removes `s` from `RETRY_DELAY` used inside `wait.sh` as sleep for macos doesn't support `<time>s`.
* fixes issue where make resource fails due to `netobserv` namespace not available before creating the `netobserv` resource.
```
echo "STORAGE_CLASS=managed-csi" > config/resources/storage.env
kubectl apply -k config/resources
namespace/chat created
namespace/minio created
configmap/storage-env-468h4442kd created
secret/minio created
secret/minio created
service/minio created
persistentvolumeclaim/minio created
deployment.apps/minio created
flowcollector.flows.netobserv.io/cluster created
clusterlogforwarder.logging.openshift.io/instance created …
```
=> fix: update manifests for OpenShift

go.mod
The following PR lessens the minor Go version requirement in `go.mod` to consider only minor releases and not specific patch releases. This allows specialized tooling as mod mirrors to use their custom go patch version (e.g. staying a bit behind) and still be able to download and mirror all dep modules.
=> Lower mininum go version req to minor releases only

hack/openshift/Makefile, hack/wait.sh
This PR resolves an issue with checking operator subscriptions. The command `wait_for_resource "$ns" get subscription/"$NAME" -o jsonpath='{.status.currentCSV}'` fails to return a non-zero exit code when no CSV was found
=> fix: update openshift related manifests

internal/pkg/loki/loki.go, pkg/domains/log/log.go, pkg/domains/netflow/netflow.go, pkg/rest/operations.go
Fixed: Loki-based stores were not using the context passed to Store.Get() so were not forwarding bearer tokens.
=> fix #73: Fix forwarding of bearer tokens for Loki-based stores.

.github/workflows/build.yml, Makefile, cmd/korrel8r/web.go, etc/korrel8r/rules/netflow.yaml, etc/korrel8r/rules/netflow_test.go, pkg/config/types.go, pkg/engine/follower.go, pkg/korrel8r/errors.go, pkg/korrel8r/korrel8r.go, pkg/rest/rest_test.go, pkg/rules/rules.go
- A rule can check pre-conditions and return blank if it does not apply to an object.
This will be ignored rather than logged as an error.
- Log similar rule evaluations with count rather than repetition.
- Log get operations with duration.
=> feat: better logging of rule and query evaluation.

etc/korrel8r/rules/k8s_test.go, internal/pkg/test/mock/mock.go, internal/pkg/test/mock/store.go, pkg/domains/alert/alert.go, pkg/domains/k8s/k8s.go, pkg/domains/log/log.go, pkg/domains/metric/metric.go, pkg/domains/netflow/netflow.go, pkg/graph/helpers_test.go, pkg/korrel8r/impl/impl.go, pkg/korrel8r/impl/object.go, pkg/korrel8r/impl/query.go, pkg/korrel8r/korrel8r.go, pkg/rest/operations.go, test/openshift/log_test.go
Replace Class.New() with class.Unmarshal() to safely encapsulate type, pointer and choice of
unmarshalling library.
- helper functions in package impl
- updated all domain/* packages.
=> refactor!: rework object unmarshalling for all domains.

cmd/korrel8r/get.go, cmd/korrel8r/main.go, internal/pkg/loki/loki.go, internal/pkg/test/mock/store.go, pkg/domains/k8s/client.go, pkg/domains/k8s/k8s.go, pkg/domains/metric/metric.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/korrel8r/constraint.go, pkg/korrel8r/impl/store.go, test/openshift/get_test.go, test/openshift/openshift.go
- openshift/get_test.go: validate store Get against real stores.
- attempted to fix limit handling in metric domain, still a problem. See FIXME.
- individual defaulting of constraint values, user can force zero values.
=> refactor: fix constraint logic, add timeout constraint.

etc/korrel8r/rules/netflow_test.go, internal/pkg/tempo/tempo.go, pkg/engine/engine.go, pkg/engine/follower.go, pkg/korrel8r/errors.go, pkg/rules/rules.go
Otherwise Go templates put a useless "<no value>" string into queries,
which makes the query invalid and produces confusing secondary errors.
=> fix #156: Enable errors for missing values in templates

pkg/graph/helpers_test.go, pkg/graph/traverse.go, pkg/graph/traverse_test.go
Previously was returning an empty graph if there were no neighbours.
=> fix: always include start node in neighbours search

Makefile, internal/pkg/test/mock/store.go, pkg/domains/k8s/k8s_test.go, pkg/korrel8r/impl/query.go
Common error: `k8s:Pod:{namespace:"foo"}` (note missing space after ':')
was parsed as a YAML map with key `namespace:"foo"`
Use strict parsing to detect this error.
=> fix: Detect bad k8s query missing space.

doc/gen/rest_api.adoc, pkg/config/configs.go, pkg/config/configs_test.go, pkg/config/duration.go, pkg/config/testdata/bad-tuning.json, pkg/config/testdata/config.json, pkg/config/types.go, pkg/engine/builder.go, pkg/korrel8r/constraint.go, pkg/rest/docs/docs.go, pkg/rest/docs/swagger.json, pkg/rest/docs/swagger.yaml, pkg/rest/helpers.go, pkg/rest/operations.go
- Add configurable tuning.requestTimetout (default 10s)
- Set context timeout on each incoming request.
- Return 206 (partial resource) if timeout is exceeded.
https://issues.redhat.com/browse/COO-563
=> fix(COO-563): Korrel8r does not interrupt over-long queries.

cmd/korrel8r/get.go, cmd/korrel8r/main.go, cmd/korrel8r/profile.go, cmd/korrel8r/web.go, doc/gen/cmd/korrel8r.adoc, doc/gen/cmd/korrel8r_describe.adoc, doc/gen/cmd/korrel8r_get.adoc, doc/gen/cmd/korrel8r_goals.adoc, doc/gen/cmd/korrel8r_list.adoc, doc/gen/cmd/korrel8r_neighbours.adoc, doc/gen/cmd/korrel8r_rules.adoc, doc/gen/cmd/korrel8r_template.adoc, go.mod, go.sum, pkg/rest/helpers.go, pkg/rest/operations.go, pkg/rest/profile.go
To help profile performance of korrel8r, added commands to run goal/neighbour searches
directly from command line, and flags to enable Go profiling.
- New commands: neighbours, goals.
- Flags: --profile and --profilePath enable profiling.
- NOTE: --profile=http enables HTTP profile server at Korrel8r endpoint.
=> feat: Added profiling and goals, neighbours commands.

Makefile
Disabled to avoid hiding sproadic test failures.
Use 'go test ...' directly to get cached tests.
=> chore: Disable test cache for 'make test'

cmd/korrel8r/cli_test.go, cmd/korrel8r/main.go, cmd/korrel8r/web_test.go, etc/korrel8r/openshift-route.yaml, etc/korrel8r/openshift-svc.yaml, etc/korrel8r/rules/all.yaml, etc/korrel8r/rules/incident.yaml, etc/korrel8r/rules/incident_test.go, etc/korrel8r/rules/k8s_test.go, etc/korrel8r/rules/rules_test.go, internal/pkg/test/domain/fixture.go, pkg/domains/alert/alert.go, pkg/domains/incident/incident.go, pkg/domains/incident/incident_domain_test.go, pkg/domains/incident/testdata/domain_test.yaml
This patch provides support for bidirection mapping between alerts and incidents, as provided by https://github.com/openshift/cluster-health-analyzer.
Apart from the incident domain implementation itself, I needed to expand the alert domain query to support passing list of maps, to be able to match multiple alerts, so that I could query all related alerts in the `IncidentToAlerts` rule.
=> feat: incidents domain

cmd/korrel8r/get.go, cmd/korrel8r/main.go, etc/korrel8r/rules/rules_test.go, pkg/config/configs.go, pkg/config/types.go, pkg/engine/builder.go, pkg/engine/engine.go, pkg/engine/stores.go, pkg/engine/traverse/async.go, pkg/engine/traverse/errors.go, pkg/engine/traverse/traverse_test.go, pkg/korrel8r/errors.go, pkg/rest/operations.go
- Initial failure to connect is logged as a warning.
- Identical errors from the same store are only logged once.
=> fix(#236): Better error logging for missing stores.

etc/korrel8r/rules/k8s.yaml, etc/korrel8r/rules/k8s_test.go, etc/korrel8r/rules/rules_test.go, internal/pkg/test/mock/store.go, internal/pkg/text/print.go, pkg/domains/k8s/client.go, pkg/domains/k8s/k8s.go, pkg/domains/k8s/k8s_test.go, pkg/domains/k8s/template_funcs.go, pkg/domains/log/direct_store.go, pkg/domains/log/log.go, pkg/engine/builder.go, pkg/engine/engine.go, pkg/engine/stores.go, pkg/korrel8r/impl/store.go, pkg/korrel8r/impl/store_test.go, pkg/korrel8r/impl/try_stores.go, pkg/korrel8r/korrel8r.go
DependentToOwner is an example of a rule that needs to distinguish cluster and namespace scoped goal
types to generate correct queries (with or without a namespace).
To allow this, rule templates can now call `k8sIsNamespaced` determine if a goal class is namespaced.
Refactoring done as a result:
- Remove Store.StoreClasses(), the Domain interface is the only source for listing classes.
- k8s.Store uses the discovery client to add classes to the Domain
- Simplified store code by removing StoreClasses everywhere.
=> fix(#263) Allow rules to handle cluster-scoped objects correctly
